# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20171002_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='post',
        ),
        migrations.DeleteModel(
            name='GroupPost',
        ),
        migrations.AddField(
            model_name='post',
            name='group_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Group'),
        ),
    ]
