# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20171004_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Post'),
        ),
    ]
