# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20171004_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
