# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20171004_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='group_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
