# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20171011_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
