# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0019_auto_20171013_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_user_likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
