# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_post_post_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_user_likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='application.Profile'),
        ),
    ]
