# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20171018_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_by',
        ),
    ]
