# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_auto_20171024_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/avatar.png', upload_to='media/images'),
        ),
    ]
