# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20171102_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='follower',
            new_name='follow',
        ),
        migrations.AddField(
            model_name='group',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
