# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0051_auto_20171102_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='follow',
        ),
        migrations.AddField(
            model_name='group',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
