# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_auto_20171102_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='follow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
